---
apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::315069654700:role/eksctl-roboshop-nodegroup-spot-NodeInstanceRole-7MvSJXdp23sV
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - roboshop-admin
      userarn: arn:aws:iam::315069654700:user/ramesh
      username: ramesh
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system